kubernetes-intro:
  - kubernetes-intro/*

kubernetes-controllers:
   - kubernetes-controllers/*

kubernetes-networks:
   - kubernetes-networks/*

 kubernetes-volumes:
   - kubernetes-volumes/*

kubernetes-security:
   - kubernetes-security/*