apiVersion: v1
kind: Service
metadata:
  name: homework-service
  namespace: homework
spec:
  type: ClusterIP
  selector:
    app: homework-site-pod
  ports:
  - name: service-port
    protocol: TCP
    port: 8000
    targetPort: site-pod-port