{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.monitoring.name }}
  namespace: {{ include "homework.namespace" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.cd.name }}
  namespace: {{ include "homework.namespace" . }}
{{- end }}